### ISSUE TITLE
Enhance ydbinstall.sh script to optionally build/install encryption plugin

### ISSUE THREAD

**Issue by nars1** [YottaDB/YDB#203]
# Final Release Note

# Description

Currently the ydbinstall.sh script installs a tarball named source.tar containing a README with instructions on how to build and install the encryption plugin. It would be nice for it to do the build/install automatically if a qualifier say --encryption_plugin is provided to it.

# Draft Release Note

ydbinstall.sh --encryption_plugin builds and installs the encryption plugin in a plugin subdirectory under the YottaDB install directory.

**Comment by shabiel** [comment]
+1

**Comment by estess** [comment]
This issue is closed on gitlab.com as #203.
