### ISSUE TITLE
Support for Grapheme Clusters in $l() and $e()

### ISSUE THREAD

**Issue by pkoper** [YottaDB/YDB#352]
YottaDB UTF-8 support in `$l()` and `$e()` functions is limited to single Code Points, but single printable "character" can be composed of multiple Code Points ([Grapheme Cluster](http://unicode.org/faq/char_combmark.html)).

Example:
Polish letter "ą" ("a" with a "little tail" called "ogonek") can encoded either as single Code Point:
`ą` ['LATIN SMALL LETTER A WITH OGONEK' (U+0105)](https://www.fileformat.info/info/unicode/char/0105/index.htm)
or as a Grapheme Cluster:
`a` ['LATIN SMALL LETTER A' (U+0061)](https://www.fileformat.info/info/unicode/char/0061/index.htm) + ` ̨` ['COMBINING OGONEK' (U+0328)](https://www.fileformat.info/info/unicode/char/0328/index.htm)

Today `$l()`, `$e()` and `$p()` have little usability in UTF-8 mode for me. Even when I store my Unicode data in normalized form (like NFC) there is no guarantee that `$e()` will not chop off a half of printable character, because not all Unicode characters can be normalized into a single Code Point.

Please, consider extending YottaDB with "grapheme cluster support mode" for `$l()`, `$e()`, `$p()`, e.g. `$l()` returns number of printable characters, not number of Code Points. Libicu have [some support](http://userguide.icu-project.org/boundaryanalysis#TOC-Character-Boundary) for grapheme clusters.

**Comment by nars1** [comment]
Piotr, regarding the 3 enhancement requests (#352, #353 and #354) you created on github, is it possible for you to create them on gitlab (https://gitlab.com/YottaDB/DB/YDB/issues) as that is where we actively maintain our Issue tracker. If not possible, that is fine. Let me know and I will create them there.

**Comment by pkoper** [comment]
Moved to [https://gitlab.com/YottaDB/DB/YDB/issues/403](https://gitlab.com/YottaDB/DB/YDB/issues/403)

**Comment by pkoper** [comment]
I have moved issues to Gitlab. You can disable issue tracking on Github, if you don't want them here - [https://help.github.com/articles/disabling-issues/](https://help.github.com/articles/disabling-issues/)

**Comment by nars1** [comment]
We have not disabled it yet just in case some user of YottaDB does not prefer creating issues on Gitlab. Thanks for moving over your issues.
