### ISSUE TITLE
Installer problem on Raspberry Pi running Ubuntu 20.04

### ISSUE THREAD

**Issue by robtweed** [YottaDB/YDB#357]
The following lines in the installer need to be amended to allow installations on the recently-available Ubuntu 20.04 version for Raspberry Pi:

	if [ "ubuntu" = "${osid}" -a 1 = `expr "$osmajorver" ">" "18"` ] || [ 1 = `expr "$osmajorver" "=" "18"` -a 1 = `expr "$osminorver" ">=" "10"` ] ; then
		if [ ! -f /lib/x86_64-linux-gnu/libtinfo.so.5 ] ; then
			echo "libtinfo5 package is required to be installed on Ubuntu 18.10 or greater using 'sudo apt-get install --no-install-recommends libtinfo5'"
			err_exit
		fi
	fi

When libtinfo5 is installed on the Raspberry Pi, it is put into /lib/aarch64-linux-gnu rather than /lib/x86_64-linux-gnu

As a workaround to get past this check in the installer, I added a symbolic link for the offending file to the /usr/lib/x86_64-linux-gnu directory and it completed successfully, with YottaDB working OK on the Raspberry Pi on Ubuntu 20.04 server.  However it would be better if the installer could be modified appropriately

Rob

**Comment by ksbhaskar** [comment]
@robtweed I have created https://gitlab.com/YottaDB/DB/YDB/-/issues/654 for this. In general, please create issues at https://gitab.com/YottaDB/YDB as that is where YottaDB software is developed. GitHub is just a backup mirror.
